services:
  db:
    image: postgres:15.4
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 7070:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
    volumes:
      - db_volume:/var/lib/postgresql/data
  app:
    restart: always
    build: .
    image: fastapi-app-image
    container_name: fastapi-app-container
    command: python main.py
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_volume:
