"""Initial migration

Revision ID: 0cb96e671011
Revises: 
Create Date: 2023-08-20 21:29:28.525034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb96e671011'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    table_productos = op.create_table('productos',
                                      sa.Column('producto_id',
                                                sa.Integer(), nullable=False),
                                      sa.Column('nombre', sa.String(),
                                                nullable=False),
                                      sa.Column('precio', sa.Float(),
                                                nullable=False),
                                      sa.Column('descripcion',
                                                sa.String(), nullable=False),
                                      sa.PrimaryKeyConstraint('producto_id'),
                                      sa.UniqueConstraint('nombre')
                                      )
    table_sucursales = op.create_table('sucursales',
                                       sa.Column('sucursal_id',
                                                 sa.Integer(), nullable=False),
                                       sa.Column('nombre', sa.String(),
                                                 nullable=False),
                                       sa.Column('descripcion',
                                                 sa.String(), nullable=False),
                                       sa.PrimaryKeyConstraint('sucursal_id')
                                       )
    table_dependientes = op.create_table('dependientes',
                                         sa.Column('dependiente_id',
                                                   sa.Integer(), nullable=False),
                                         sa.Column(
                                             'nombre', sa.String(), nullable=False),
                                         sa.Column('dui', sa.String(),
                                                   nullable=False),
                                         sa.Column(
                                             'sucursal_id', sa.Integer(), nullable=False),
                                         sa.ForeignKeyConstraint(
                                             ['sucursal_id'], ['sucursales.sucursal_id'], ),
                                         sa.PrimaryKeyConstraint(
                                             'dependiente_id')
                                         )
    table_inventarios = op.create_table('inventarios',
                                        sa.Column('inventario_id',
                                                  sa.Integer(), nullable=False),
                                        sa.Column(
                                            'nombre', sa.String(), nullable=False),
                                        sa.Column(
                                            'sucursal_id', sa.Integer(), nullable=False),
                                        sa.ForeignKeyConstraint(
                                            ['sucursal_id'], ['sucursales.sucursal_id'], ),
                                        sa.PrimaryKeyConstraint(
                                            'inventario_id')
                                        )
    table_regentes = op.create_table('regentes',
                                     sa.Column('regente_id',
                                               sa.Integer(), nullable=False),
                                     sa.Column('nombre', sa.String(),
                                               nullable=False),
                                     sa.Column('jvpqf', sa.String(),
                                               nullable=False),
                                     sa.Column('sucursal_id',
                                               sa.Integer(), nullable=False),
                                     sa.ForeignKeyConstraint(
                                         ['sucursal_id'], ['sucursales.sucursal_id'], ),
                                     sa.PrimaryKeyConstraint('regente_id')
                                     )
    table_pedidos = op.create_table('pedidos',
                                    sa.Column(
                                        'pedido_id', sa.Integer(), nullable=False),
                                    sa.Column(
                                        'cantidad', sa.Integer(), nullable=False),
                                    sa.Column('estado', sa.Enum('ingresado', 'en proceso',
                                                                'finalizado', name='estado_pedido'), nullable=False),
                                    sa.Column('fecha', sa.DateTime(), server_default=sa.text(
                                        'CURRENT_TIMESTAMP'), nullable=False),
                                    sa.Column('producto_id',
                                              sa.Integer(), nullable=False),
                                    sa.Column('inventario_id',
                                              sa.Integer(), nullable=False),
                                    sa.ForeignKeyConstraint(
                                        ['inventario_id'], ['inventarios.inventario_id'], ),
                                    sa.ForeignKeyConstraint(
                                        ['producto_id'], ['productos.producto_id'], ),
                                    sa.PrimaryKeyConstraint('pedido_id')
                                    )
    table_transferencias = op.create_table('transferencias',
                                           sa.Column('transferencia_id',
                                                     sa.Integer(), nullable=False),
                                           sa.Column('fecha', sa.DateTime(), server_default=sa.text(
                                               'CURRENT_TIMESTAMP'), nullable=False),
                                           sa.Column('inventario_origen_id',
                                                     sa.Integer(), nullable=False),
                                           sa.Column('inventario_destino_id',
                                                     sa.Integer(), nullable=False),
                                           sa.Column(
                                               'pedido_id', sa.Integer(), nullable=False),
                                           sa.ForeignKeyConstraint(['inventario_destino_id'], [
                                               'inventarios.inventario_id'], ),
                                           sa.ForeignKeyConstraint(['inventario_origen_id'], [
                                               'inventarios.inventario_id'], ),
                                           sa.ForeignKeyConstraint(
                                               ['pedido_id'], ['pedidos.pedido_id'], ),
                                           sa.PrimaryKeyConstraint(
                                               'transferencia_id')
                                           )

    op.bulk_insert(table_productos, [
                   {'producto_id': 1, 'nombre': 'aspirina',
                       'precio': 0.99, 'descripcion': 'aspirina mk'},
                   {'producto_id': 2, 'nombre': 'cofal',
                       'precio': 1.99, 'descripcion': 'cofal fuerte'},
                   {'producto_id': 3, 'nombre': 'vitamina c',
                       'precio': 2.99, 'descripcion': 'masticable'},
                   {'producto_id': 4, 'nombre': 'suero',
                       'precio': 3.99, 'descripcion': 'frutas'},
                   {'producto_id': 5, 'nombre': 'curitas',
                    'precio': 4.99, 'descripcion': 'impermeables'}])

    op.bulk_insert(table_sucursales, [
                   {'sucursal_id': 1, 'nombre': 'san nicolas',
                       'descripcion': 'metrocentro'},
                   {'sucursal_id': 2, 'nombre': 'economicas', 'descripcion': 'ayutuxtepeque'}])

    op.bulk_insert(table_dependientes, [
                   {'sucursal_id': 1, 'nombre': 'antonio',
                       'dui': '123456-1', 'sucursal_id': 1},
                   {'sucursal_id': 2, 'nombre': 'ivan',
                       'dui': '654321-2', 'sucursal_id': 1},
                   {'sucursal_id': 3, 'nombre': 'edgar', 'dui': '234567-3', 'sucursal_id': 2}])

    op.bulk_insert(table_inventarios, [
                   {'dependiente_id': 1, 'nombre': 'bodega', 'sucursal_id': 1},
                   {'dependiente_id': 2, 'nombre': 'venta', 'sucursal_id': 1},
                   {'dependiente_id': 3, 'nombre': 'devolucion', 'sucursal_id': 1},
                   {'dependiente_id': 4, 'nombre': 'bodega', 'sucursal_id': 2},
                   {'dependiente_id': 5, 'nombre': 'venta', 'sucursal_id': 2},
                   {'dependiente_id': 6, 'nombre': 'devolucion', 'sucursal_id': 2}])

    op.bulk_insert(table_regentes, [
                   {'regente_id': 1, 'nombre': 'juan',
                       'jvpqf': '1234567', 'sucursal_id': 1},
                   {'regente_id': 2, 'nombre': 'carlos', 'jvpqf': '789456123', 'sucursal_id': 2}])

    op.bulk_insert(table_pedidos, [
                   {'pedido_id': 1, 'cantidad': 10, 'estado': 'finalizado',
                       'producto_id': 1, 'inventario_id': 1},
                   {'pedido_id': 2, 'cantidad': 20, 'estado': 'finalizado',
                       'producto_id': 2, 'inventario_id': 1},
                   {'pedido_id': 3, 'cantidad': 30, 'estado': 'finalizado', 'producto_id': 3, 'inventario_id': 1}])

    op.bulk_insert(table_transferencias, [
                   {'transferencia_id': 1, 'inventario_origen_id': 1, 'inventario_destino_id': 1, 'pedido_id': 1}])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transferencias')
    op.drop_table('pedidos')
    op.drop_table('regentes')
    op.drop_table('inventarios')
    op.drop_table('dependientes')
    op.drop_table('sucursales')
    op.drop_table('productos')
    op.execute("""DROP TYPE estado_pedido""")
    # ### end Alembic commands ###
